version: "3.7"

services:
  db_challenge_dynamox:
    image: postgres
    container_name: db_challenge_dynamox
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gen_products
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
